### ISSUE TITLE
CSRF needs to be disabled?

### ISSUE THREAD

**Issue by JerseyMilker** [msvitok/Laravel-Adminer#2]
It seems I need to disable CSRF protection middleware for Adminer to work.  Do you know of way to just disable CSRF middleware on the Adminer route only?

**Comment by JerseyMilker** [comment]
Actually, it looks like Laravel 5.1 is addressing this.  In 5.1, you will be able to add an array of any URI's that you want CSRF middleware to ignore to your \App\Http\Middleware\VerifyCsrfToken class:
`protected $except = ['adminer'];`

Maybe you want to mention this in the readme?

**Comment by msvitok** [comment]
You're right, thanks for noticing.
For Laravel 5.0, I think the easiest way is to create a custom VerifyCsrfToken middleware that excludes selected routes:

```

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;

class CustomVerifyCsrfToken extends VerifyCsrfToken {

    protected $excludedRoutes = ['adminer'];

	public function handle($request, Closure $next)
	{
        if ($this->isExcludedRoute($request)){
            return $next($request);
        } else {
            return parent::handle($request, $next);
        }
	}

    private function isExcludedRoute($request)
    {
        if (count($request->segments()) > 0
            && in_array($request->segment(1), $this->excludedRoutes)){
            return true;
        } else {
            return false;
        }
    }
}

```

And then use that as CSRF middleware in `Kernel.php`
```
protected $middleware = [
	'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
	'Illuminate\Cookie\Middleware\EncryptCookies',
	'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
	'Illuminate\Session\Middleware\StartSession',
	'Illuminate\View\Middleware\ShareErrorsFromSession',
	'Path\To\CustomVerifyCsrfToken',
];
```

**Comment by msvitok** [comment]
As for Laravel 5.1, good point, I'll update the documentation with the workaround.

**Comment by JerseyMilker** [comment]
I'm using the `$except` attribute for 'adminer' now with 5.1's VerifyCsrfToken class.  Works excellent :)

**Comment by msvitok** [comment]
Documentation updated, thanks :) Now should work with 5.1 as well, closing.

**Comment by JerseyMilker** [comment]
Looks great, thanks!
